sudo: false
language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py install

# command to run tests
script: nosetests -v -a '!travis_exclude,!uses_network'

