#!/usr/bin/env python
#
# Usage: python build_profile.py <endpoint>
# Outputs a profile that can be used for a given endpoint with poll_profiles, including all the available sets for that endpoint

import sys, os
from amara.thirdparty import json, httplib2
                                                                
LIMIT = "9999"
AKARA_BASE = "http://localhost:8889/"
AKARA_SETS = AKARA_BASE + "oai.listsets.json?limit=" + LIMIT + "&endpoint="
AKARA_RECORDS = AKARA_BASE + "oai.listrecords.json?endpoint="

def build_profile(endpoint_URL):

    H = httplib2.Http('/tmp/.pollcache')
    H.force_exception_as_status_code = True          
    resp, content = H.request(AKARA_SETS + endpoint_URL)
    if not resp[u'status'].startswith('2'):
        print >> sys.stderr, '  HTTP error ('+resp[u'status']+') resolving URL: '+endpoint_URL

    profile = {}
    profile[u'endpoint_URL'] = AKARA_RECORDS + endpoint_URL + u'&oaiset='
    profile[u'subresources'] = []                
   
    try:
        oaisets = json.loads(content)
        for oaiset in oaisets:
           profile[u'subresources'].append(oaiset[0])
             
    except Exception as e:
        profile = None                               

    return json.dumps(profile)

if __name__ == '__main__':

    if not sys.argv[1:]:
         print >> sys.stderr, 'OAI endpoint required. Aborting.'
         sys.exit(1)

    print build_profile(sys.argv[1])
