#!/usr/bin/env python
#
# Usage: python poll_profiles.py <profiles-glob> <enrichment-service-URI>

import sys, os, glob, fnmatch
import base64
import datetime, time
from itertools import groupby
from urllib import urlencode
from amara.thirdparty import json, httplib2
from amara.lib.iri import is_absolute, join
from amara import bindery

# FIXME Turns out this isn't always correct. Sometimes Series files are located in
# different directories than its Item files. No clear deterministic path between
# them, so will have to find the file instead using globbing
#ARC_RELATED_FILE = lambda srcdir, htype, hid: os.path.join(os.path.dirname(srcdir+os.sep),"%s_%s.xml"%(htype.replace(' ',''),hid))
ARC_RELATED_FILE = lambda srcdir, htype, hid: os.path.join(os.sep.join(os.path.dirname(srcdir+os.sep).split(os.sep)[:-1]),"*","%s_%s.xml"%(htype.replace(' ',''),hid))

ENRICH = None # enrichment service URI
H = httplib2.Http('/tmp/.pollcache')
H.force_exception_as_status_code = True

def process_profile(out,profile_f):
    global ENRICH

    fprof = open(profile_f,'r')
    try:
        profile = json.load(fprof)
    except Exception as e:
        profile = None

    fprof.close()

    if not profile:
        print >> sys.stderr, 'Error reading source profile.'
        return False

    # Pause in secs between collection ingests
    sleep = profile.get(u'sleep',0)

    ENRICH = out

    subResources = profile.get(u'subresources')
    ptype = profile.get(u'type').lower()
    if not subResources or len(subResources)==0: # i.e. all subresources
        process = TYPE_PROCESSORS.get((ptype,'all'))
        if not process:
            print >> sys.stderr, "The ingest of all %s collections is not supported at this time"%(ptype.upper())
            sys.exit(1)

        process(profile)
    else:
        process = TYPE_PROCESSORS((ptype,'coll'))
        if not process:
            print >> sys.stderr, "The ingest of individual %s collections is not supported at this time"%(ptype.upper())
            sys.exit(1)

        for subr in subResources:
            process(profile,subr)
            time.sleep(sleep)

    # Update profile metadata and save
    profile[u'last_checked'] = datetime.datetime.now().isoformat()
    fprof = open(profile_f,'w')
    json.dump(profile,fprof,indent=4)
    fprof.close()

    return True

def process_arc_all(profile):
    src_URL = profile.get('endpoint_URL')
    assert src_URL.startswith('file:/') # assumes no authority and the non-broken use of //
    src_dir = src_URL[5:]

    collections = {} # this could get big unless we can figure out a way to scope it
    for (root, dirs, files) in os.walk(src_dir):
        print "root = "+root
        items = []
        for filename in fnmatch.filter(files, 'Item_*.xml'):
            item_fn = os.path.join(root,filename)
            item_f = open(item_fn,'r')
            item_parsed = bindery.parse(item_f)
            item = {}

            item['title'] = unicode(item_parsed.archival_description.title)
            item['handle'] = [unicode(item_parsed.archival_description.arc_id)] # FIXME OAI leak
            item['created'] = {'start': unicode(item_parsed.archival_description.created_timestamp),
                               'end': unicode(item_parsed.archival_description.created_timestamp) }
            if hasattr(item_parsed.archival_description,'scope_content_note'):
                item['description'] = unicode(item_parsed.archival_description.scope_content_note)

            print repr(item)

            hier_items = item_parsed.archival_description.hierarchy.hierarchy_item
            for hi in hier_items:
                htype = unicode(hi.hierarchy_item_lod)
                if not htype.lower() == 'series': continue # only interested in Series objects as collections

                hid = hi.hierarchy_item_id

                if hid not in collections:
                    # Parse the series/collection file
                    try:
                        print >> sys.stderr, "Looking for Series file with arc-id = "+root 
                        hier_fname = glob.glob(ARC_RELATED_FILE(root,htype,hid))[0]
                        print >> sys.stderr, "   Found file = "+hier_fname
                        hier_f = open(hier_fname,'r')
                    except Exception as e:
                        print >> sys.stderr, "Couldn't find referenced Series file (%s) from %s"%((hier_fname,item_fn))
                        continue

                    hier = bindery.parse(hier_f)
                    hier_f.close()

                    cid = unicode(hier.archival_description.arc_id)
                    assert hid == cid, "Unexpected difference in ARC IDs between Item reference and retrieved Series"

                    coll = {}
                    coll['handle'] = [cid]
                    coll['label'] = unicode(hier.archival_description.title)
                    coll['items'] = []
                    collections[cid] = coll
                else:
                    coll = collections[cid]

                coll['items'].append(item)

            items.append(item)

    for cid in collections:
        # FIXME need way to pass in the label
        enrich_coll(profile,cid,json.dumps({'items':collections[cid]['items']}))

def enrich_coll(profile,subr,content):
    # Enrich retrieved data
    global ENRICH
    headers = {
        "Content-Type": "application/json",
        "Pipeline-Coll": ','.join(profile["enrichments_coll"]),
        "Pipeline-Rec": ','.join(profile["enrichments_rec"]),
        "Source": profile['name'],
        "Contributor": base64.b64encode(json.dumps(profile.get(u'contributor',{})))
    }
    if subr:
        headers["Collection"] = subr

    resp, content = H.request(ENRICH,'POST',body=content,headers=headers)
    if not str(resp.status).startswith('2'):
        print >> sys.stderr, '  HTTP error with enrichment service: '+repr(resp)

def process_oai_coll(profile,subr):
    # For now, a simplifying assumption that string concatenation produces a
    # full URI from the combination of the endpoint URL and each subresource id.
    # Better might be a single field listing all URIs but unclear how that extends
    # to other protocols.

    # If multiple requests are required to harvest all information from a resource, they will
    # give us 'resumption tokens' after each request until we are done. Passing the resumption
    # token will provide the next batch of results

    request_more, resumption_token = True, ""
    while request_more:
        endpoint = profile[u'endpoint_URL'] + subr
        if resumption_token:
            endpoint += '&' + urlencode({'resumption_token': resumption_token})
        print >> sys.stderr, endpoint

        resp, content = H.request(endpoint)
        if not resp[u'status'].startswith('2'):
            print >> sys.stderr, '  HTTP error ('+resp[u'status']+') resolving URL: ' + endpoint
            continue
        endpoint_content = json.loads(content)
        resumption_token = endpoint_content['resumption_token']

        enrich_coll(profile,subr,content)

        request_more = resumption_token is not None and len(resumption_token) > 0

TYPE_PROCESSORS = {
    ('arc','coll'): None,
    ('arc','all'): process_arc_all,
    ('oai','coll'): process_oai_coll,
    ('oai','all'): None,
}

if __name__ == '__main__':

    for profile in glob.iglob(sys.argv[1]):
        print >> sys.stderr, 'Processing profile: '+profile
        process_profile(sys.argv[2], profile)
