#!/usr/bin/env python
"""
Script to rollback a provider's data to a previous ingestion.

Usage:
    $ python rollback_ingestion.py provider_name ingestion_sequence
"""
import sys
import argparse
from dplaingestion.couch import Couch

def define_arguments():
    """Defines command line arguments for the current script
    """
    parser = argparse.ArgumentParser()
    name_help = "The provider's name as listed in the provider's profile"
    sequence_help = "The ingestion sequence to rollback to"
    parser.add_argument("provider_name", help=name_help, type=str)
    parser.add_argument("ingestion_sequence", help=sequence_help, type=int)
    return parser

def main(argv):
    couch = Couch()
    parser = define_arguments()
    args = parser.parse_args(argv[1:])
    resp = couch.rollback(args.provider_name, args.ingestion_sequence)
    print >> sys.stderr, resp

if __name__ == "__main__":
    main(sys.argv)
